DROP SCHEMA IF EXISTS queue;
CREATE SCHEMA IF NOT EXISTS queue;

-- USE queue;

CREATE TABLE log (
  id        INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  system    VARCHAR(24)  NOT NULL,
  channel   VARCHAR(24)  NOT NULL,
  status    VARCHAR(24)  NOT NULL,
  message   VARCHAR(999) NOT NULL,
  dtCreated TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dtUpdated TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
